# VARIABLES

[[exercises]]
name = "main函数"
path = "exercises/C程序基础结构/main函数.c"
hint = """
Hint: 提示一: 跟我读: "main   m  a  i  n"
      提示二: 英   文 分号!!!!!!!!!!!
"""

[[exercises]]
name = "综合练习1"
path = "exercises/C程序基础结构/exam.c"
hint = """
Hint:  恭喜你，终于跨进C语言的大门了！
       让我们看看，你是否已经准备好了吧！
       请你试着改正以下程序的错误：
"""
